### ISSUE TITLE
Links Blockieren

### ISSUE THREAD

**Issue by strich3** [zImPinguin/Discord-Global-Bot#1]
Links werden nicht blockiert! kannst du des reincoden?

**Comment by zImPinguin** [comment]
Werde ich beim nächsten Update adden.

**Comment by zImPinguin** [comment]
Sollte ich eigentlich jetzt reingecodet haben wenn es nicht so ist schreib hier nochmal.

**Comment by strich3** [comment]
ok

**Comment by strich3** [comment]
Wo ist der code? xd

**Comment by strich3** [comment]
Ich meine danke das du das überhaupt machst :)
